// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(EscolaContext))]
    [Migration("20201017132928_api")]
    partial class api
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.models.Escola", b =>
                {
                    b.Property<decimal>("id")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Escola");
                });

            modelBuilder.Entity("api.models.Turma", b =>
                {
                    b.Property<decimal>("id")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("escolaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("escolaid");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("api.models.Turma", b =>
                {
                    b.HasOne("api.models.Escola", "escola")
                        .WithMany("turmas")
                        .HasForeignKey("escolaid");
                });
#pragma warning restore 612, 618
        }
    }
}
